#!/bin/bash
import os
import py_compile

source = os.environ.get("PYFILE")
if source:
    py_compile.compile(source, cfile=source + "c")
    print(f"Compiled {source} to {source}c")
else:
    print("$PYFILE is either empty or not set")
